baseurl = "/"
title = "Life musings"
author = "Clinton Oyogo"
copyright = "Copyright © 2020,clinton oyogo."
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"
relativeurls = false

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = "Life on this side of eternity can be misty...'we can only see through a glass, dimly...'"
introDescription = "oyogo"
contentSharing = "Glad if you'll be kind enough to share the link with your friends."

[social]

linkedin = "oyogo-clinton-53359198"
twitter = "OyogoDavid"

#https://lifemusings.netlify.app